#!/usr/bin/perl

use FindBin;
use lib $FindBin::Bin;

my $file = $ARGV[0];
my $dest = $ARGV[1];

my $deps = `$FindBin::Bin/get_dependencies_for_binary $file`;
my @lines = split('\n', $deps);

system("cp -n $file $dest");

foreach my $val (@lines)
{
    chomp($val);
    system("$FindBin::Bin/copy_converter_file_and_dependencies $val $dest");
}
