name: Dependency Check
on:
  workflow_dispatch:

  schedule:
    # Running once a week
    - cron:  '12 3 * * 4'

jobs:
  build:
    name: check dependency
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Get ISMRMRD latest tag
        run: |
          tagInfo=$(curl -s https://api.github.com/repos/ismrmrd/ismrmrd/tags | jq -r '.[0]')
          tag=$(echo "$tagInfo" | jq -r '.name')
          sha=$(echo "$tagInfo" | jq -r '.commit.sha')
          echo "$sha" > dependencies/ismrmrd
          echo "ISMRMRD_TAG=$tag" >> "$GITHUB_ENV"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          title: "Update ISMRMRD dependency to ${{ env.ISMRMRD_TAG }}"
          body: "ISMRMRD has a new release: [${{ env.ISMRMRD_TAG }}](https://github.com/ismrmrd/ismrmrd/releases/tag/${{ env.ISMRMRD_TAG }})"
          commit-message: "Update ISMRMRD dependency to ${{ env.ISMRMRD_TAG }}"